### PR TITLE
Implemented 'click' event for notifications

### PR DESCRIPTION
**Pull request by andy-lee-eng**
Make Notification an EventEmitter and implement in all three containers

### CODE REVIEW

**Review by BenLambertNcl — APPROVED** [review]
LGTM. Got a bit confused with the empty `innerAddEventListener` functions but rereading the code it seems like the correct behaviour, maybe worth adding a quick comment such as 
> Not needed as listeners are added in the parent class

But might not be necessary

**Comment by andy-lee-eng** [comment]
Yep. The innerAddEventListener stuff was needed because the Browser/OpenFin/Electron versions of Window all did it slightly differently. They all needed to do something though, so I made it abstract to force the derived class to implement it.

Now that it seems two of the Notification implementations don't actually need them, I'm thinking it might be simpler to make them non-abstract (with a no-op default implementation), so we can just leave them out if not required.

**Comment by BenLambertNcl** [comment]
Yeah that sounds like a good idea. Im happy to leave that for a separate PR and just merge this as is

**Comment by andy-lee-eng** [comment]
It'll be quick to do, so I may as well just do it now. Update coming soon...

**Review by BenLambertNcl — APPROVED** [review]

**Comment by andy-lee-eng** [comment]
Almost there - looks like I broke a bunch of other Window tests by putting that set-size code in.

**Comment by BenLambertNcl** [comment]
Yeah im looking into it now. Fixed that, but there seems to be another problem with openfin tests timing out

**Comment by andy-lee-eng** [comment]
OpenFin tests are all passing for me now.

**Comment by BenLambertNcl** [comment]
LGTM, I have a fix for the OpenFin tests timing out too, adding `containerjs-api-openfin` as a dependency to `api-tests`. You can include it in this PR or I can make a separate one?

**Comment by andy-lee-eng** [comment]
Ah, ok.
I removed that dependency (and replaced it with the browser/openfin bundle `containerjs-api-bundle` instead), so that the tests would run in the same way that the real application runs, and also because the `container-api-utility` library is included in the bundle but not in the openfin version.

I guess I still had `container-api-openfin` in my `node_modules` though. Do you know why the the dependency is still needed? Does it need it in order to run `OpenFin` maybe?

**Comment by BenLambertNcl** [comment]
Yeah, its needed for the ssf-openfin cli that we use to launch openfin. If ssf-openfin was installed globally (like on my machine) the tests will pass. Probably the same scenario if it was still inside node_modules.

**Pull request merged**
