### PR TITLE
Add tests for message service

### PR DESCRIPTION
**Pull request by BenLambertNcl**
Added tests for the messaging service, mainly testing the logic for sending and subscribing to particular windows and topics. Tests were added for the message service to make sure that multiple parts of the API could be tested with Spectron.

### CODE REVIEW

**Review by ColinEberhardt — APPROVED** [review]
Looks good to me. A couple of thoughts ...

Is there some common config / setup code from the Windows tests that could be put in a common location?

You could probably remove the repetitive promise chaining with something like the following:

```
const chainPromises = (promises) => promises.reduce((acc, cur) => acc.then(curr);
}, promises[0]);
```

Which you'd use as follows:
```
const steps = [
  () => selectWindow(1),
  () => executeStuff(),
  ()  => selectWindow(2)
]
return chainPromises(steps);
```

(I've not tested that!)

**Comment by BenLambertNcl** [comment]
Regarding the first point, yes there are some thing that are repeated and can be moved (for example, `executeAsyncJavascript`). Would `test-helpers.js` be a suitable name (I know a lot of people dislike the name 'helper' or similar).

I will take a look at your second suggestion. For me though, I think the promise chaining reads slightly better (but that's personal preference I suppose :) )

**Review by AndyMJones — APPROVED** [review]
Looks good to me but I agree with Colin that that the steps way looks a little bit nicer if it works.

**Comment by BenLambertNcl** [comment]
Ill look at adding it in then :)

**Comment by ColinEberhardt** [comment]
> Ill look at adding it in then :)

Surely you mean you'll look at adding it in then().then().then().then()?

**Comment by ColinEberhardt** [comment]
> Ill look at adding it in then :)

Surely you mean you'll look at adding it in then().then().then().then()?

**Comment by BenLambertNcl** [comment]
Made those changes.

**Pull request merged**
