### PR TITLE
Add interface and property tests to documentation

### LINKED ISSUE #197: Tests that are not mapped to API methods
We have a few tests which are not mapped to the API:

```
$ npm run docs
...
unable to find the method ssf.MessageService.receive within the typescript documentation
unable to find the method ssf.Window() within the typescript documentation
unable to find the method ssf.Window(center) within the typescript documentation
unable to find the method ssf.Window(maxHeight) within the typescript documentation
unable to find the method ssf.Window(minHeight) within the typescript documentation
unable to find the method ssf.Window(x) within the typescript documentation
unable to find the method ssf.Window(y) within the typescript documentation
unable to find the method ssf.Window.isVisible within the typescript documentation
unable to find the method ssf.Window.maximized within the typescript documentation
unable to find the method ssf.WindowEvent.blur within the typescript documentation
unable to find the method ssf.WindowEvent.closed within the typescript documentation
unable to find the method ssf.WindowEvent.focus within the typescript documentation
unable to find the method ssf.WindowEvent.hide within the typescript documentation
unable to find the method ssf.WindowEvent.maximize within the typescript documentation
unable to find the method ssf.WindowEvent.minimize within the typescript documentation
unable to find the method ssf.WindowEvent.move within the typescript documentation
unable to find the method ssf.WindowEvent.resize within the typescript documentation
unable to find the method ssf.WindowEvent.restore within the typescript documentation
unable to find the method ssf.WindowEvent.show within the typescript documentation
```

### PR DESCRIPTION
**Pull request by JDawes-ScottLogic**
Add tests for interfaces and properties to the documentation.

Fixes #197

### CODE REVIEW

**Review by BenLambertNcl — APPROVED** [review]
👍. @ColinEberhardt would it be possible to add @JDawes-ScottLogic to the CLA bot and as a contributor to the repo please :-)

**Comment by andy-lee-eng** [comment]
@ColinEberhardt does John just need to be added to the Scott Logic organisation in GitHub?
@JDawes-ScottLogic maybe it@scottlogic.co.uk can do this for you?

I don't think anything needed to be done to add me to the CLA bot - once I started using the right GitHub account (which is already in the SL organisation), it just worked (unless anyone did something I wasn't aware of).

**Comment by JDawes-ScottLogic** [comment]
@DevAndyLee That would make sense. I'll drop IT a mail and see if that sorts it.

**Comment by BenLambertNcl** [comment]
Ah maybe thats it then! 👍

**Comment by JDawes-ScottLogic** [comment]
Well I'm in the SL organisation now, but that doesn't seem to have done much (other than break the Details link for cla-bot!)

**Comment by andy-lee-eng** [comment]
Maybe we need to get cla-bot to re-run its check? e.g. if you merge/rebase and push again?

**Comment by JDawes-ScottLogic** [comment]
Raised https://github.com/symphonyoss/ContainerJS/pull/273 to try this instead, but that's got the same problem. I wonder if it's related to me not being made a Collaborator yet?

**Comment by andy-lee-eng** [comment]
I think the Collaborators list is just a list of people who have contributed commits to the project.

**Comment by andy-lee-eng** [comment]
No wait, that's the "Contributors" from the top menu. Where are "Collaborators" set?

**Comment by JDawes-ScottLogic** [comment]
They're set in the settings tab for the repo. Not sure what permissions are required to add them, though.

**Comment by BenLambertNcl** [comment]
I think only colin has permission to do that.

**Review by andy-lee-eng — APPROVED** [review]

**Comment by ColinEberhardt** [comment]
The @ssf-cla-bot[bot] is an instance of the cla-bot (which I wrote), but is managed / maintained by Symphony Foundation. I don't have visibility of their list of contributors with signed CLAs. However, Scott Logic has a CLA that covers all employees.

@maoo @pmonks can one of you add @JDawes-ScottLogic to the list of contributors? Thanks!

**Comment by pmonks** [comment]
@JDawes-ScottLogic - you've been added to the whitelist, but it may take a short period (up to 15 mins or so) for the change to propagate.

**Comment by pmonks** [comment]
@ColinEberhardt just as an FYI, I typically register previously unknown users on (at worst) a weekly basis.  That information comes from [here](https://metrics.symphony.foundation/app/kibana#/dashboard/C_SSF_Unknown).  If you know of additional ScottLogic employees (or anyone else who would be legally covered under the ScottLogic CCLA - subcontractors etc.), feel free to let me know and I can add them proactively.

**Comment by ColinEberhardt** [comment]
@ssf-cla-bot[bot] check

**Comment by ColinEberhardt** [comment]
@cla-bot check

**Comment by ColinEberhardt** [comment]
@maoo looks like the bot isn't properly configured, it should have kicked in due to the above comments!

**Comment by maoo** [comment]
@ssf-cla-bot[bot] check

**Comment by maoo** [comment]
@ColinEberhardt - I see that "ssf-cla-bot bot added the cla-signed label 2 hours ago"; this is the expected behaviour right? I wonder why it took so long, will check logs and let you know

**Pull request merged**
